import type { Product, Order } from "@/lib/types"

export const products: Product[] = [
  {
    id: "1",
    name: "Whey Protein",
    description: "Premium whey protein isolate for muscle recovery and growth.",
    price: 12.99,
    image: "/images/casein-protein.png",
    category: "Protein",
    tags: ["Protein", "Muscle Recovery", "Post-Workout"],
    bestSeller: true,
    ingredients: "Whey Protein Isolate, Cocoa Powder, Natural Flavors, Stevia Extract, Xanthan Gum.",
    nutritionalInfo: "Serving Size: 30g, Protein: 24g, Carbohydrates: 3g, Fat: 1g, Calories: 120",
  },
  {
    id: "2",
    name: "Casein Protein",
    description: "Slow-digesting protein ideal for overnight muscle recovery.",
    price: 9.99,
    image: "/images/casein-protein.png",
    category: "Protein",
    tags: ["Protein", "Slow Release", "Overnight Recovery"],
    bestSeller: false,
    ingredients: "Micellar Casein, Natural Flavors, Salt, Stevia Extract, Guar Gum.",
    nutritionalInfo: "Serving Size: 30g, Protein: 24g, Carbohydrates: 3g, Fat: 1g, Calories: 120",
  },
  {
    id: "3",
    name: "Creatine",
    description: "Pure micronized creatine monohydrate for strength and performance.",
    price: 12.99,
    image: "/images/casein-protein.png",
    category: "Performance",
    tags: ["Strength", "Performance", "Muscle"],
    bestSeller: true,
    ingredients: "100% Micronized Creatine Monohydrate.",
    nutritionalInfo: "Serving Size: 5g, Creatine Monohydrate: 5g",
  },
  {
    id: "4",
    name: "Multivitamin",
    description: "Complete daily multivitamin with essential nutrients.",
    price: 18.99,
    image: "/images/casein-protein.png",
    category: "Vitamins",
    tags: ["Daily Health", "Immunity", "Wellness"],
    bestSeller: true,
    ingredients: "Vitamin A, Vitamin C, Vitamin D, Vitamin E, B-Complex Vitamins, Zinc, Magnesium, Calcium.",
    nutritionalInfo: "Serving Size: 1 tablet, Contains 100% Daily Value of 23 essential vitamins and minerals",
  },
  {
    id: "5",
    name: "Vitamin D",
    description: "High-potency vitamin D3 for immune support and bone health.",
    price: 9.99,
    image: "/images/casein-protein.png",
    category: "Vitamins",
    tags: ["Immunity", "Bone Health", "Wellness"],
    bestSeller: false,
    ingredients: "Vitamin D3 (Cholecalciferol), Olive Oil, Gelatin, Glycerin.",
    nutritionalInfo: "Serving Size: 1 softgel, Vitamin D3: 5000 IU (125 mcg)",
  },
  {
    id: "6",
    name: "Fish Oil",
    description: "Omega-3 rich fish oil for heart and brain health.",
    price: 12.99,
    image: "/images/casein-protein.png",
    category: "Wellness",
    tags: ["Heart Health", "Brain Health", "Omega-3"],
    bestSeller: true,
    ingredients: "Fish Oil Concentrate, Gelatin, Glycerin, Purified Water.",
    nutritionalInfo: "Serving Size: 1 softgel, Total Omega-3 Fatty Acids: 1000mg, EPA: 500mg, DHA: 250mg",
  },
  {
    id: "7",
    name: "Probiotic",
    description: "Advanced probiotic blend for digestive and immune health.",
    price: 18.99,
    image: "/images/casein-protein.png",
    category: "Digestive Health",
    tags: ["Gut Health", "Immunity", "Digestion"],
    bestSeller: false,
    ingredients: "Lactobacillus acidophilus, Bifidobacterium lactis, Lactobacillus plantarum, Prebiotic Fiber Blend.",
    nutritionalInfo: "Serving Size: 1 capsule, 50 Billion CFU, 12 Probiotic Strains",
  },
  {
    id: "8",
    name: "Probiotic+",
    description: "Premium probiotic with added digestive enzymes.",
    price: 11.99,
    image: "/images/casein-protein.png",
    category: "Digestive Health",
    tags: ["Gut Health", "Enzymes", "Digestion"],
    bestSeller: false,
    ingredients: "Lactobacillus acidophilus, Bifidobacterium lactis, Digestive Enzyme Blend, Prebiotic Fiber.",
    nutritionalInfo: "Serving Size: 1 capsule, 30 Billion CFU, 10 Probiotic Strains, 5 Digestive Enzymes",
  },
]

export const orders: Order[] = [
  {
    id: "ORD-001",
    customer: {
      name: "John Smith",
      email: "john.smith@example.com",
      address: "123 Main St",
      city: "New York",
      zip: "10001",
      country: "USA",
    },
    items: [
      { product: products[0], quantity: 2 },
      { product: products[3], quantity: 1 },
    ],
    status: "pending",
    date: "2023-05-15",
    total: 44.97,
  },
  {
    id: "ORD-002",
    customer: {
      name: "Jane Doe",
      email: "jane.doe@example.com",
      address: "456 Park Ave",
      city: "Los Angeles",
      zip: "90001",
      country: "USA",
    },
    items: [
      { product: products[2], quantity: 1 },
      { product: products[5], quantity: 1 },
    ],
    status: "fulfilled",
    date: "2023-05-14",
    total: 25.98,
  },
  {
    id: "ORD-003",
    customer: {
      name: "Robert Johnson",
      email: "robert.johnson@example.com",
      address: "789 Oak St",
      city: "Chicago",
      zip: "60007",
      country: "USA",
    },
    items: [
      { product: products[1], quantity: 1 },
      { product: products[4], quantity: 2 },
      { product: products[6], quantity: 1 },
    ],
    status: "cancelled",
    date: "2023-05-13",
    total: 48.96,
  },
]
